### ISSUE TITLE
linux运行会生成乱码

### ISSUE THREAD

**Issue by mikelty** [imcaspar/gpt2-ml#100]
你好我在colab那个链接上面跑通了代码，在linux上面就会出乱码。比如“今天天气真好”输入，他就会输出“天天真……”（后面多为英文单词，无空格，无意义）。请教一下怎么解。

目前的尝试：
1.增加了meta和index文件（用了colab上面的wget命令）。
2.根据requirements-gpu.txt搭建了虚拟环境。
3.SHA256校验了model checkpoint 220000，跟colab上面可以正常运行的版本是一样的。
4.locale改成中文```export LC_ALL=zh_CN.UTF-8; python demo.py ...```。
5.把```print('🍺Model loaded. \nInput something please:⬇️')```中的两个表情去掉了，恢复旁边的代码。

还有一点就是我现在必须把demo.py移到gpt2-ml文件夹下，不然train包就找不到。

多谢解答。

**Comment by imcaspar** [comment]
readme 中给出的两个版本 model 词表是不通用的

**Comment by mikelty** [comment]
的确，我demo里面换clue-vocab就好了。感谢！
