### ISSUE TITLE
Google Colab 运行的时候，文件无法下载到，会报错403

### ISSUE THREAD

**Issue by ligenxun** [imcaspar/gpt2-ml#110]
提供的：https://colab.research.google.com/github/imcaspar/gpt2-ml/blob/master/pretrained_model_demo.ipynb 的在线文档中，执行下载的时候，会报错403文件权限问题。这个可能是谷歌的在线网盘分享权限导致的问题，我使用了其他的谷歌网盘是没有问题的，就这个文档里的模型没法下载。

**Comment by imcaspar** [comment]
gdown.pl failed,
plz uncomment the line with !python scripts/down_gdrive_file.py, and rerun
