### ISSUE TITLE
ERROR 404: Not Found.

### ISSUE THREAD

**Issue by ZhuYanzhen1** [imcaspar/gpt2-ml#126]
When I ran the first paragraph in google colab, the following error was reported.
```bash
--2022-05-17 12:15:37--  https://docs.google.com/uc?id=1mT_qCQg4AWnAXTwKfsyyRWCRpgPrBJS3&export=download
Resolving docs.google.com (docs.google.com)... 142.251.5.139, 142.251.5.101, 142.251.5.113, ...
Connecting to docs.google.com (docs.google.com)|142.251.5.139|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

Couldn't download the file :-(
```

**Comment by zxkmm** [comment]
This repo is not maintained anymore so i created a fork and fixed this problem.
https://github.com/zxkmm/gpt2-ml-fixed

**Comment by ZhuYanzhen1** [comment]
> This repo is not maintained anymore so i created a fork and fixed this problem. https://github.com/zxkmm/gpt2-ml-fixed

Thanks!
