### ISSUE TITLE
up主是不是把模型训练成近似恒等式了？

### ISSUE THREAD

**Issue by ashora** [imcaspar/gpt2-ml#14]
看了一下生成结果，来自问题1的引用：
【想要学习更多内容，请关注微信号：b##ms##h##200##1】【文章来源：艾锐文化】点击下
方阅读原文查看更多内容。↓↓↓##↓##↓##↓##↓##↓##↓##↓##↓##↓##↓##↓##↓##↓##↓##↓##↓##↓点击"阅读原文"【查看更多内容】

回头特地看了一下训练参数和字典，不是分词，按理说“文章来源”训练出来可以接受，但“艾锐文化”输出就有恒等输出的可能了，这是命名词，不应该有这么强的联系。
这一点在Morizeyao/GPT2-Chinese中，也有一位台湾的朋友遇到，训练出来的模型总是倾向于输出原文。。。

所以，我的问题其实是openAI这个大力出奇迹的超大模型，究竟是在生成还是复现？

**Comment by imcaspar** [comment]
建议用 colab demo 实测下生成结果

**Comment by ashora** [comment]
自回归模型本来就是生成原文的啊，我举得例子不是生成的结果吗？直接从#1问题里面抽取的

**Comment by sqlkrad** [comment]
如果复现就能骗过人类，结论只能是人类根本没有智能，人就是在不断地重复 -。-

**Comment by sgalal** [comment]
<div lang="zh-CN">

@ashora 实际上「艾锐文化」是 AI 自创的名字，网上是搜不到的。这个模型生成的很多实体都是即使能查到也是跟前文不相关的。

</div>
