### ISSUE TITLE
[Discussion] 百度云链接

### ISSUE THREAD

**Issue by frkhit** [imcaspar/gpt2-ml#23]
[gogle drive](https://drive.google.com/open?id=1n_5-tgPpQ1gqbyLPbP1PwiFi2eo7SWw_) 中的模型，已上传到[百度云](https://pan.baidu.com/s/14EnvAhQBEL9Cwn7KDruBtQ)， 提取码`y4k6`。 模型大小约`5.2GB`。

**Comment by imcaspar** [comment]
感谢上传
在下一个版本模型发布前这个 issue 会暂时 open
鉴于百度云不保证哈希一致性，建议使用前对比下文件的 sha256
sha256: 4a6e5124df8db7ac2bdd902e6191b807a6983a7f5d09fb10ce011f9a073b183e

**Comment by ZJiaBin** [comment]
ValueError: The passed save_path is not a valid checkpoint:
出现了这样的错误，请问各位有遇到过嘛？

**Comment by zhaolulul** [comment]
> ValueError: The passed save_path is not a valid checkpoint:
> 出现了这样的错误，请问各位有遇到过嘛？
我也遇到了你解决了吗

**Comment by fanyunli** [comment]
求提供model.ckpt-220000.data-00000-of-00001的百度云链接。google drive下载，提示无法下载，暂未找到原因。

**Comment by ghosthamlet** [comment]
model.ckpt-220000.data-00000-of-00001百度云盘链接，在gpt2-ml/mega-clue-tok-tf目录下: pan.baidu.com/s/16tL4Bmoh6jPy0cOND0YyeA 提取码: 84dh

**Comment by chenjun0210** [comment]
百度链接下载好慢。。。google链接那个下载需要权限

**Comment by iblisylvie** [comment]
> [gogle drive](https://drive.google.com/open?id=1n_5-tgPpQ1gqbyLPbP1PwiFi2eo7SWw_) 中的模型，已上传到[百度云](https://pan.baidu.com/s/14EnvAhQBEL9Cwn7KDruBtQ)， 提取码`y4k6`。 模型大小约`5.2GB`。

colab案例里面是ckpt 220000的模型，百度云盘里面是100000的模型，请问哪里可以下载到您这边提供的model.ckpt-220000.data-00000-of-00001

**Comment by imcaspar** [comment]
百度云链接已添加，下载后建议与 readme 中提供的 sha256 进行比对，确认是否一致
#107
