### ISSUE TITLE
[Bug] name your bug

### ISSUE THREAD

**Issue by HamQ** [imcaspar/gpt2-ml#28]
## Environment

- Python version: Python 3.7.5 x64
- OS: Win10 18363.476
- (Optional) Other libraries and their versions:
pandas==0.24.2
regex==2019.4.14
h5py==2.9.0
numpy==1.16.2
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tqdm==4.31.1
requests==2.22.0

## Error messages, stack traces, or logs

> D:\gpt2-ml-master>python scripts/interactive_conditional_samples.py   -model_config_fn configs/mega.json   -model_ckpt models/mega/model.ckpt-100000   -eos_token 511   -min_len 200   -samples 10
> Traceback (most recent call last):
>   File "scripts/interactive_conditional_samples.py", line 10, in <module>
>     from train.modeling import GroverModel, GroverConfig, sample
> ModuleNotFoundError: No module named 'train'
> 

## Additional context (optional)

我本地跑i下结果是这样 为什么呢？难道就是由于我没独显嘛  谢谢

**Comment by imcaspar** [comment]
`PYTHONPATH=$(pwd) python3 scripts/interactive_conditional_samples.py`
看起来是环境变量的问题

**Comment by HamQ** [comment]
谢谢  大佬  晚上回去了再试试   会主要留意一下环境变量了这次 谢谢

**Comment by zhouguang1972** [comment]
这个我遇到过，export PYTHONPATH=/.../gpt2-ml（安装目录），就好了。

**Comment by HamQ** [comment]
@zhouguang1972 
@imcaspar 

谢谢两位  环境变量是问题 
我把我的run.bat改成下面这样后看上去好多了
```
@echo off
set PYTHONPATH=%~dp0
echo %PYTHONPATH%
python scripts/interactive_conditional_samples.py ^
  -model_config_fn configs/mega.json ^
  -model_ckpt models/mega/model.ckpt-100000 ^
  -eos_token 511 ^
  -min_len 200 ^
  -samples 10
```

输出是这样的， 估计我的tensorflow还是不对 我再搜1下吧， 谢谢两位
```
D:\gpt2-ml-master>run.bat
D:\gpt2-ml-master\
Traceback (most recent call last):
  File "scripts/interactive_conditional_samples.py", line 19, in <module>
    from tensorflow.python.util import module_wrapper as deprecation
ImportError: cannot import name 'module_wrapper' from 'tensorflow.python.util' (C:\Program Files\Python37\lib\site-packages\tensorflow\python\util\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/interactive_conditional_samples.py", line 21, in <module>
    from tensorflow.python.util import deprecation_wrapper as deprecation
ImportError: cannot import name 'deprecation_wrapper' from 'tensorflow.python.util' (C:\Program Files\Python37\lib\site-packages\tensorflow\python\util\__init__.py)
  
```

**Comment by zgd716** [comment]
> 输出是这样的， 估计我的tensorflow还是不对 我再搜1下吧， 谢谢两位

大佬你的好了吗?我的也报这个错误
