### ISSUE TITLE
想问一下这个模型的结构和原始的GPT-2的模型一样吗？

### ISSUE THREAD

**Issue by nonstopfor** [imcaspar/gpt2-ml#31]
如题，因为我想把这个模型的预训练好的参数加载到GPT-2模型当中去，看起来这是Grover模型？

**Comment by guotong1988** [comment]
同问

**Comment by imcaspar** [comment]
结构和参数量和 GPT-2 是一致的
@nonstopfor 如果是指加载到 huggingface 的 Transformers 中，暂时没有做过相关测试
之前的 issue 中有相关尝试，也欢迎提交你的测试结果
