### ISSUE TITLE
The release time of 1.5B model trained on 50G corpus

### ISSUE THREAD

**Issue by xinyx** [imcaspar/gpt2-ml#37]
First of all, **GREAT THANKS** for the release of the big Chinese GPT-2 model! I have tested with some primes and the results look very good.

So I am very looking forward to the release of the model trained with even more data and more epochs, could I know the exact release time of it? since the author said it should be due on the early Dec.

Thanks very much!

**Comment by Raymondhhh90** [comment]
关注

**Comment by ewrfcas** [comment]
watch for it

**Comment by imcaspar** [comment]
sorry for the late reply, plz ref #71
