### ISSUE TITLE
加载模型错误

### ISSUE THREAD

**Issue by bliunlpr** [imcaspar/gpt2-ml#39]
我下载了开源的模型，显示如下错误：
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./model.ckpt-100000: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
请问是什么问题？谢谢

**Comment by ares89** [comment]
解决了吗

**Comment by imcaspar** [comment]
请先试用 colab demo，本地运行时可以参考 demo 中的 Prerequisites
