### ISSUE TITLE
[Bug] name y本地运行出现tensorflow版本不匹配的问题 

### ISSUE THREAD

**Issue by ScottishFold007** [imcaspar/gpt2-ml#41]
我把5G多的模型下载到本地，现在本地跑起来，结果发现tensorflow的版本问题，半天都没解决，请问你默认运行的版本是多少？以及对应的依赖库？谢谢大神！

**Comment by imcaspar** [comment]
依赖版本请见 https://github.com/imcaspar/gpt2-ml/blob/master/requirements-gpu.txt
