### ISSUE TITLE
[Feature] 期待能与uber的PPLM结合起来

### ISSUE THREAD

**Issue by uuleaf** [imcaspar/gpt2-ml#48]
## Description
因为现在生成语句是通顺的，但是还是容易逃离主题，期待能与uber的PPLM结合起来
https://github.com/huggingface/transformers/blob/master/examples/pplm/run_pplm.py

## Additional information

老师这个代码并不是用的GPT2的官方程序，我自己没有头绪无从下手
或者是老师能加入词袋功能也是可以的

可有偿：QQ2027725943，感谢老师百忙中查阅

**Comment by ScottishFold007** [comment]
我基于抱抱脸的transformers实现了下，用于对对子，不脱离主题，比如对出写春天的下联，效果还不错：

![Uploading image.png…]()
山 抹 微 云 ， 天 粘 衰 草 ， 画 角 声 断 谯 门 <sep> 水 流 明 月 ， 风 送 残 花 ， 诗 心 韵 动 江 楼 
桃 花 也 解 愁 ， 点 点 飘 红 玉 <sep> 柳 絮 才 知 春 ， 丝 丝 缠 绿 烟 
新 年 都 未 有 芳 华 ， 二 月 初 惊 见 草 芽 <sep> 旧 友 已 然 成 故 事 ， 三 更 又 起 闻 花 香
国 破 山 河 在 ， 城 春 草 木 深 <sep> 人 逢 盛 世 来 ， 民 乐 天 地 新
红豆生南国，春来发几枝 <sep> 青山在北疆，秋去又一年
我看青山多妩媚  <sep> 谁知碧水不妖娆

**Comment by ZJiaBin** [comment]
> 我基于抱抱脸的transformers实现了下，用于对对子，不脱离主题，比如对出写春天的下联，效果还不错：
> 
> 
> 山 抹 微 云 ， 天 粘 衰 草 ， 画 角 声 断 谯 门 |水 流 明 月 ， 风 送 残 花 ， 诗 心 韵 动 江 楼
> 桃 花 也 解 愁 ， 点 点 飘 红 玉 | 柳 絮 才 知 春 ， 丝 丝 缠 绿 烟
> 新 年 都 未 有 芳 华 ， 二 月 初 惊 见 草 芽 |旧 友 已 然 成 故 事 ， 三 更 又 起 闻 花 香
> 国 破 山 河 在 ， 城 春 草 木 深 | 人 逢 盛 世 来 ， 民 乐 天 地 新
> 红豆生南国，春来发几枝 |青山在北疆，秋去又一年
> 我看青山多妩媚 | 谁知碧水不妖娆
您好，请问方便描述一下细节吗，如何将这个模型用在transformers上呢，我看issues 似乎大家转pytorch模型都不太顺利~万分感谢！

**Comment by imcaspar** [comment]
暂时没有实现 pplm 的计划

**Comment by huanghonggit** [comment]
@ZJiaBin 哈喽请问你转pytorch模型成功了吗

**Comment by huanghonggit** [comment]
@ScottishFold007  哈喽，您好，能请教你是怎么实现的嘛~
