### ISSUE TITLE
[Bug] 不能下载文件

### ISSUE THREAD

**Issue by zgxtao** [imcaspar/gpt2-ml#49]
> Below is the issue template. You can fill each part then submit your issue. 
> Or you can just delete all of these and describe your questions in you-like style. 
> But please remember: the more detailed info you offered, the greater possibility your problem will be solved. 😜

Please write a clear and concise description of what the bug is.

## 
fatal: destination path 'gpt2-ml' already exists and is not an empty directory.
/content/gpt2-ml
models/mega/model.c     [ <=>                ]   3.02K  --.-KB/s    in 0s      
Couldn't download the file :-(

Please write a clear and concise description of what you expected to happen.
solve the problem

## Environment
Colab
- Python version:
- OS:
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs
fatal: destination path 'gpt2-ml' already exists and is not an empty directory.
/content/gpt2-ml
models/mega/model.c     [ <=>                ]   3.02K  --.-KB/s    in 0s      
Couldn't download the file :-(

## Steps to reproduce

1.starts when
2.error occurs

**Comment by imcaspar** [comment]
Thx for the report.
Download url should be fixed in the new colab notebook & readme

**Comment by zgxtao** [comment]
辛苦了，谢谢

Caspar ZHANG <notifications@github.com>于2020年2月27日 周四下午6:22写道：
