### ISSUE TITLE
 No module named 'train'

### ISSUE THREAD

**Issue by icefairy** [imcaspar/gpt2-ml#52]
from train.modeling import GroverModel, GroverConfig, sample
ModuleNotFoundError: No module named 'train'

Im using conda create -n ml2 python=3.7
here is pip list:
Package              Version                  
-------------------- -------------------      
absl-py              0.9.0                    
astor                0.8.1                    
attrs                19.3.0                   
backcall             0.1.0                    
bleach               3.1.0                    
certifi              2019.11.28               
chardet              3.0.4                    
colorama             0.4.3                    
decorator            4.4.1                    
defusedxml           0.6.0                    
entrypoints          0.3                      
gast                 0.3.3                    
grpcio               1.27.2                   
h5py                 2.10.0                   
idna                 2.8                      
importlib-metadata   1.5.0                    
ipykernel            5.1.4                    
ipython              7.12.0                   
ipython-genutils     0.2.0                    
ipywidgets           7.5.1                    
jedi                 0.16.0                   
Jinja2               2.11.1                   
joblib               0.14.1                   
jsonschema           3.2.0                    
jupyter              1.0.0                    
jupyter-client       5.3.4                    
jupyter-console      6.1.0                    
jupyter-core         4.6.1                    
Keras-Applications   1.0.8                    
Keras-Preprocessing  1.1.0                    
Markdown             3.2.1                    
MarkupSafe           1.1.1                    
mistune              0.8.4                    
mkl-fft              1.0.15                   
mkl-random           1.1.0                    
mkl-service          2.3.0                    
mock                 4.0.1                    
nbconvert            5.6.1                    
nbformat             5.0.4                    
notebook             6.0.3                    
numpy                1.18.1                   
pandas               0.24.2                   
pandocfilters        1.4.2                    
parso                0.6.1                    
pickleshare          0.7.5                    
pip                  20.0.2                   
prometheus-client    0.7.1                    
prompt-toolkit       3.0.3                    
protobuf             3.11.4                   
Pygments             2.5.2                    
pyreadline           2.1                      
pyrsistent           0.15.7                   
python-dateutil      2.8.1                    
pytz                 2019.3                   
pywin32              227                      
pywinpty             0.5.7                    
pyzmq                18.1.1                   
qtconsole            4.6.0                    
regex                2019.4.14                
requests             2.22.0                   
scikit-learn         0.22.1                   
scipy                1.4.1                    
Send2Trash           1.5.0                    
setuptools           45.2.0.post20200210      
six                  1.14.0                   
tensorboard          1.13.1                   
tensorflow           1.13.1                   
tensorflow-estimator 1.13.0                   
termcolor            1.1.0                    
terminado            0.8.3                    
testpath             0.4.4                    
tornado              6.0.3                    
tqdm                 4.31.1                   
traitlets            4.3.3                    
urllib3              1.25.8                   
wcwidth              0.1.8                    
webencodings         0.5.1                    
Werkzeug             1.0.0                    
wheel                0.34.2                   
widgetsnbextension   3.5.1                    
wincertstore         0.2                      
zipp                 2.2.0

**Comment by cncbec** [comment]
I have this problem.
did you solved it?

**Comment by wind91725** [comment]
I have this problem too.
did you solved it?

**Comment by icefairy** [comment]
> I have this problem.
> did you solved it?

no

**Comment by icefairy** [comment]
> I have this problem.
> did you solved it?

no

**Comment by imcaspar** [comment]
thx for the report, this issue should be fixed in #71

**Comment by kunpeng199494** [comment]
before you import traing, you should make sure you have append the traing.py into sys, just like this:
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
