### ISSUE TITLE
用GPT2对对子，效果很赞

### ISSUE THREAD

**Issue by ScottishFold007** [imcaspar/gpt2-ml#53]
以下上联是人写的（可以自行百度），下联都是机器对出来的，效果很赞，估计你都忘记原来的词句了：
【上联】悠悠柳岸落红霞 【下联】寂寂春窗落絮声
【上联】悠悠柳岸落红霞 【下联】袅潺松阴披晚节
【上联】悠悠柳岸落红霞 【下联】郁郁荷塘映彩虹
【上联】悠悠柳岸落红霞 【下联】冉冉荷塘生绿烟
【上联】悠悠柳岸落红霞 【下联】款款江堤荡碧波
【上联】漠漠水田飞白鹭 【下联】茫茫云路隐青山
【上联】悠悠柳岸落红霞 【下联】款款荷塘荡碧波
【上联】漠漠水田飞白鹭 【下联】滔滔波浪涌黄河
【上联】漠漠水田飞白鹭 【下联】悠悠柳岸荡轻舟
【上联】帝道真知，如今都成过去事 【下联】民心所向，自古都是往来人
【上联】旷古圣人才，能以逍遥通世法 【下联】平生名利事，自然淡泊得真如
【上联】公谊不妨私，平日政见分弛，肝胆至今推挚友 【下联】人生何足论？此时心怀坦荡，襟怀自古仰高风
【上联】公谊不妨私，平日政见分弛，肝胆至今推挚友 【下联】人间原是纸，吾意情犹激励，江山从古胜文章
【上联】公谊不妨私，平日政见分弛，肝胆至今推挚友 【下联】子孙何必羡？此时贤亲义士，风霜从古更哀师
【上联】英雄作事无它，只坚忍一心，能成世界能成我 【下联】壮志凌云有志，纵风流万里，不负春秋不负人
【上联】英雄作事无它，只坚忍一心，能成世界能成我 【下联】人间多情至此，在消磨半句，可笑天伦最是家
【上联】共和误民国？民国误共和？百世而后，再平是狱 【下联】以人为天下，天下为己任：万物之中，一物之间
【上联】共和误民国？民国误共和？百世而后，再平是狱 【下联】同心作主人，天地为公道：一尘不染，无欲则刚
【上联】共和误民国？民国误共和？百世而后，再平是狱 【下联】一语关己身，子孙成大孝！四德可先，既往以终
【上联】我以我血荐轩辕 【下联】自有英名垂宇宙
【上联】漠漠水田飞白鹭 【下联】盈盈竹坞醉秋风
![image](https://user-images.githubusercontent.com/36957508/75602201-ff9e1f80-5afd-11ea-80bd-3bd16d481dc7.png)
PS:基于Uber提出的PPLM（Plug and Play Language Models: a Simple Approach to Controlled Text Generation），用词袋控制生成主题不偏离，比如下面的对联，我输入上联，下联紧扣“春天“这个主题，貌似效果还不错：

Uploading image.png…
**山 抹 微 云 ， 天 粘 衰 草 ， 画 角 声 断 谯 门** |水 流 明 月 ， 风 送 残 花 ， 诗 心 韵 动 江 楼
**桃 花 也 解 愁 ， 点 点 飘 红 玉** | 柳 絮 才 知 春 ， 丝 丝 缠 绿 烟
**新 年 都 未 有 芳 华 ， 二 月 初 惊 见 草 芽** |旧 友 已 然 成 故 事 ， 三 更 又 起 闻 花 香
**国 破 山 河 在 ， 城 春 草 木 深** | 人 逢 盛 世 来 ， 民 乐 天 地 新
**红豆生南国，春来发几枝** |青山在北疆，秋去又一年
**我看青山多妩媚** | 谁知碧水不妖娆
**天阶夜色凉如水* | 人面春风醉若泥

【上联】春山暖日和风，阑干楼阁帘栊 【下联】暮水朝云细雨，别院花木兰芳   
【上联】京口瓜洲一水间，钟山只隔数重山 【下联】巴人竹叶千杯里，花雨不沾半缕尘  
【上联】春风又绿江南岸，明月何时照我还 【下联】柳岸常依燕子楼，繁花不处有谁家 
【上联】碧玉妆成一树高，万条垂下绿丝绦 【下联】红日照亮千畴艳，百鸟争鸣金缕机
【上联】碧玉妆成一树高，万条垂下绿丝绦 【下联】红云照亮千峰翠，百鸟唤来金雀巢
【上联】天阶夜色凉如水 【下联】曲径花声艳若霞    
【上联】春风又绿江南岸 【下联】细雨还红陌上桃   
【上联】春风又绿江南岸 【下联】旭日重临岭上林    
【上联】春风又绿江南岸 【下联】细雨还红陌上桃   
【上联】我看青山多妩媚 【下联】谁言梅水不芬芳  
名篇《春江花月夜》的下句改写，估计你都忘记实际的下句了，哈哈哈：
【上联】春江潮水连海平，海上明月共潮生 【下联】古塔风云绕山青，峰顶彩霞共霭晖
【上联】滟滟随波千万里，何处春江无月明 【下联】幽幽如幻五十年，此间尘世有风流
【上联】江流宛转绕芳甸，月照花林皆似霰 【下联】山势氤氲浮翠霭，风梳杨柳欲飞烟
【上联】斜月沉沉藏海雾，碣石潇湘无限路 【下联】春江漫卷漾烟雨，长河日夜有缘人
【上联】不知江月待何人，但见长江送流水 【下联】只向渔家寻旧迹，试问何处答耕桑
【上联】白云一片去悠悠，青枫浦上不胜愁 【下联】碧水千层横漠漠，赤雁南来正飞歌
【上联】鸿雁长飞光不度，鱼龙潜跃水成文 【下联】渔家小住月相随，鸥鹭往来船载歌
【上联】此时相望不相闻，愿逐月华流照君 【下联】何处觅人犹有约？欲邀仙子去还家
【上联】江畔何人初见月？江月何年初照人 【下联】天下有地可藏龙，海风哪处可观心
【上联】江天一色无纤尘，皎皎空中孤月轮 【下联】杨柳千丝犹有梦，蒙蒙地上满船灯

【上联】转朱阁，低绮户，照无眠，不应有恨 【下联】举大樽，邀清风，斟古月，何必无言
【上联】举杯邀明月，对影成三人 【下联】临屏赏白梅，随心咏一声
【上联】胸无点墨 【下联】口有余香
【上联】十口心思,思君思国思社稷 【下联】一腔热泪，恨己恨他恨人民
【上联】破釜沉舟，三千越甲可吞吴 【下联】乘风破浪，六十回头能啸秦
【上联】卧薪尝胆，三千越甲可吞吴 【下联】伏釜沉舟，四海扬波能缚蛟
【上联】三杯两盏淡酒，怎敌他晚来风急 【下联】一醉几巡闲言，便知是梦了诗成
【上联】燕草如碧丝，秦桑低绿枝 【下联】夕阳似金锦，柳枝悬红线
【上联】庭院深深深几许 【下联】春山隐隐隐孤身
【上联】庭院深深深几许 【下联】梅花点点点春香

【上联】漠漠水田飞白鹭，阴阴夏木啭黄鹂 【下联】绵绵秋雨润禾苗，处处山林映玉蝉
【上联】漠漠水田飞白鹭，阴阴夏木啭黄鹂 【下联】依依山径落斜阳，袅袅炊烟绕翠竹

【上联】五岭横云一片青，衡山积雪终年白 【下联】九州铺锦八方绿，林海堆红满眼春
【上联】五岭横云一片青，衡山积雪终年白 【下联】双峰映日十分碧，函谷春深几度红

【上联】洞庭浩渺通长江，春来水涨连天碧 【下联】华阁崔巍迎盛会，时过车奔遍地红
【上联】慷慨歌燕市，从容作楚囚 【下联】清音醉杏坛，寂寞成唐诗
【上联】赤橙黄绿青蓝紫，谁持彩练当空舞 【下联】柴米油盐酱醋茶，客为力军作秀言

【上联】茫茫九派流中国，沉沉一线穿南北 【下联】滔滔三江溯太行，滚浩万年贯古今
【上联】茫茫九派流中国，沉沉一线穿南北 【下联】浩浩千春耀上京，滚滚三江舞东西
【上联】茫茫九派流中国，沉沉一线穿南北 【下联】荡荡东洋过大江，滚滚千流过古今
【上联】茫茫九派流中国，沉沉一线穿南北 【下联】悠悠三湾锁西洋，滚滚千商过东西

【上联】横空出世，莽昆仑，阅尽人间春色 【下联】下笔挥毫，成巨匠，绘出生态蓝图
【上联】飞起玉龙三百万，搅得周天寒彻 【下联】勾起渭河数千年，汇来秦土风情
【上联】飞起玉龙三百万，搅得周天寒彻 【下联】携来佛法五千言，引来妙谛玄机
【上联】我失骄杨君失柳，杨柳轻扬直上重霄九 【下联】春回大地雪迎雷，地冰乍起先苏万物锦
【上联】夜长天色总难明，寂寞披衣起坐数寒星 【下联】人静心灰都是幻，相思枕席轻敲几尺丝
【上联】夜长天色总难明，寂寞披衣起坐数寒星 【下联】人在画图空有趣，从容拄杖谈玄一醉开
【上联】夜长天色总难明，寂寞披衣起坐数寒星 【下联】金风玉露悄然冷，相思倚枕听啼无归人
【上联】六月天兵征腐恶，万丈长缨要把鲲鹏缚 【下联】一支玉笔写春秋，千年遗恨永铭将士碑

【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】五千兵戈俱喧阗，水归淮北空余屈子魂
【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】千余老幼尽欢颜，联惊海外长怀赵与韩
【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】三千志士竞登攀，功成世界全凭武与文 【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】三千豪杰竞风流，舟行淮北犹歌宋与唐
【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】七旬岁月竞风流，梦牵河北长扬楚与吴
【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】我来江畔谒崇陵，遗烈八年壮国威 注：崇陵是光绪皇帝爱新觉罗.载湉和叶赫那拉·静芬（隆裕太后）的合葬陵寝 【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】回首江山换新颜，春花一样笑杨梅
【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】重归海岛护同盟，风雨千秋祭祖师

【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】且邀明月饮新醪，玉液千杯酹泰山 注：醪， 新酿的酒；酹，把酒浇在地上，表示祭奠
【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】今观国粹谱新篇，联对千家颂党恩
【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】重归梓里吊忠魂，天地三千开后人
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】帝无前事佐明主，却图一战扫烟云
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】人生向上多自力，始终一战统山河
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】死犹未免埋白骨，亦如一抔葬忠魂
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】人心臣首怀赤胆，未能一死竟平生
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】人思此处访遗庙，未经千载是英雄
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】不由后死赴江汉，岂独一败论英雄
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】谁似臣心报国门？至今百战识英雄
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】自悲吾辈失青鬓，竟成千古痛元君
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】我来仙界横紫气，定披七彩绣河山
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】不为世界哭元老，且持三字表心胸
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】世风余韵遗青史，岂惟五代识君臣
【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】世间此地留忠骨，长教千载祀英雄

**Comment by zgxtao** [comment]
这个对对联是需要在模型里设定特殊的参数吗？为什么我在Colab跑的时候，只有一个输入起始语句的输入框？

**Comment by ScottishFold007** [comment]
这是我用pytorch训练的，不是基于现有的这一套玩意，其中还有很多trick

**Comment by zgxtao** [comment]
上传一套colab玩玩啥

**Comment by zhaolulul** [comment]
> 以下上联是人写的（可以自行百度），下联都是机器对出来的，效果很赞，估计你都忘记原来的词句了：
> 【上联】悠悠柳岸落红霞 【下联】寂寂春窗落絮声
> 【上联】悠悠柳岸落红霞 【下联】袅潺松阴披晚节
> 【上联】悠悠柳岸落红霞 【下联】郁郁荷塘映彩虹
> 【上联】悠悠柳岸落红霞 【下联】冉冉荷塘生绿烟
> 【上联】悠悠柳岸落红霞 【下联】款款江堤荡碧波
> 【上联】漠漠水田飞白鹭 【下联】茫茫云路隐青山
> 【上联】悠悠柳岸落红霞 【下联】款款荷塘荡碧波
> 【上联】漠漠水田飞白鹭 【下联】滔滔波浪涌黄河
> 【上联】漠漠水田飞白鹭 【下联】悠悠柳岸荡轻舟
> 【上联】帝道真知，如今都成过去事 【下联】民心所向，自古都是往来人
> 【上联】旷古圣人才，能以逍遥通世法 【下联】平生名利事，自然淡泊得真如
> 【上联】公谊不妨私，平日政见分弛，肝胆至今推挚友 【下联】人生何足论？此时心怀坦荡，襟怀自古仰高风
> 【上联】公谊不妨私，平日政见分弛，肝胆至今推挚友 【下联】人间原是纸，吾意情犹激励，江山从古胜文章
> 【上联】公谊不妨私，平日政见分弛，肝胆至今推挚友 【下联】子孙何必羡？此时贤亲义士，风霜从古更哀师
> 【上联】英雄作事无它，只坚忍一心，能成世界能成我 【下联】壮志凌云有志，纵风流万里，不负春秋不负人
> 【上联】英雄作事无它，只坚忍一心，能成世界能成我 【下联】人间多情至此，在消磨半句，可笑天伦最是家
> 【上联】共和误民国？民国误共和？百世而后，再平是狱 【下联】以人为天下，天下为己任：万物之中，一物之间
> 【上联】共和误民国？民国误共和？百世而后，再平是狱 【下联】同心作主人，天地为公道：一尘不染，无欲则刚
> 【上联】共和误民国？民国误共和？百世而后，再平是狱 【下联】一语关己身，子孙成大孝！四德可先，既往以终
> 【上联】我以我血荐轩辕 【下联】自有英名垂宇宙
> 【上联】漠漠水田飞白鹭 【下联】盈盈竹坞醉秋风
> ![image](https://user-images.githubusercontent.com/36957508/75602201-ff9e1f80-5afd-11ea-80bd-3bd16d481dc7.png)
> PS:基于Uber提出的PPLM（Plug and Play Language Models: a Simple Approach to Controlled Text Generation），用词袋控制生成主题不偏离，比如下面的对联，我输入上联，下联紧扣“春天“这个主题，貌似效果还不错：
> 
> Uploading image.png…
> **山 抹 微 云 ， 天 粘 衰 草 ， 画 角 声 断 谯 门** |水 流 明 月 ， 风 送 残 花 ， 诗 心 韵 动 江 楼
> **桃 花 也 解 愁 ， 点 点 飘 红 玉** | 柳 絮 才 知 春 ， 丝 丝 缠 绿 烟
> **新 年 都 未 有 芳 华 ， 二 月 初 惊 见 草 芽** |旧 友 已 然 成 故 事 ， 三 更 又 起 闻 花 香
> **国 破 山 河 在 ， 城 春 草 木 深** | 人 逢 盛 世 来 ， 民 乐 天 地 新
> **红豆生南国，春来发几枝** |青山在北疆，秋去又一年
> **我看青山多妩媚** | 谁知碧水不妖娆
> *_天阶夜色凉如水_ | 人面春风醉若泥
> 
> 【上联】春山暖日和风，阑干楼阁帘栊 【下联】暮水朝云细雨，别院花木兰芳
> 【上联】京口瓜洲一水间，钟山只隔数重山 【下联】巴人竹叶千杯里，花雨不沾半缕尘
> 【上联】春风又绿江南岸，明月何时照我还 【下联】柳岸常依燕子楼，繁花不处有谁家
> 【上联】碧玉妆成一树高，万条垂下绿丝绦 【下联】红日照亮千畴艳，百鸟争鸣金缕机
> 【上联】碧玉妆成一树高，万条垂下绿丝绦 【下联】红云照亮千峰翠，百鸟唤来金雀巢
> 【上联】天阶夜色凉如水 【下联】曲径花声艳若霞
> 【上联】春风又绿江南岸 【下联】细雨还红陌上桃
> 【上联】春风又绿江南岸 【下联】旭日重临岭上林
> 【上联】春风又绿江南岸 【下联】细雨还红陌上桃
> 【上联】我看青山多妩媚 【下联】谁言梅水不芬芳
> 名篇《春江花月夜》的下句改写，估计你都忘记实际的下句了，哈哈哈：
> 【上联】春江潮水连海平，海上明月共潮生 【下联】古塔风云绕山青，峰顶彩霞共霭晖
> 【上联】滟滟随波千万里，何处春江无月明 【下联】幽幽如幻五十年，此间尘世有风流
> 【上联】江流宛转绕芳甸，月照花林皆似霰 【下联】山势氤氲浮翠霭，风梳杨柳欲飞烟
> 【上联】斜月沉沉藏海雾，碣石潇湘无限路 【下联】春江漫卷漾烟雨，长河日夜有缘人
> 【上联】不知江月待何人，但见长江送流水 【下联】只向渔家寻旧迹，试问何处答耕桑
> 【上联】白云一片去悠悠，青枫浦上不胜愁 【下联】碧水千层横漠漠，赤雁南来正飞歌
> 【上联】鸿雁长飞光不度，鱼龙潜跃水成文 【下联】渔家小住月相随，鸥鹭往来船载歌
> 【上联】此时相望不相闻，愿逐月华流照君 【下联】何处觅人犹有约？欲邀仙子去还家
> 【上联】江畔何人初见月？江月何年初照人 【下联】天下有地可藏龙，海风哪处可观心
> 【上联】江天一色无纤尘，皎皎空中孤月轮 【下联】杨柳千丝犹有梦，蒙蒙地上满船灯
> 
> 【上联】转朱阁，低绮户，照无眠，不应有恨 【下联】举大樽，邀清风，斟古月，何必无言
> 【上联】举杯邀明月，对影成三人 【下联】临屏赏白梅，随心咏一声
> 【上联】胸无点墨 【下联】口有余香
> 【上联】十口心思,思君思国思社稷 【下联】一腔热泪，恨己恨他恨人民
> 【上联】破釜沉舟，三千越甲可吞吴 【下联】乘风破浪，六十回头能啸秦
> 【上联】卧薪尝胆，三千越甲可吞吴 【下联】伏釜沉舟，四海扬波能缚蛟
> 【上联】三杯两盏淡酒，怎敌他晚来风急 【下联】一醉几巡闲言，便知是梦了诗成
> 【上联】燕草如碧丝，秦桑低绿枝 【下联】夕阳似金锦，柳枝悬红线
> 【上联】庭院深深深几许 【下联】春山隐隐隐孤身
> 【上联】庭院深深深几许 【下联】梅花点点点春香
> 
> 【上联】漠漠水田飞白鹭，阴阴夏木啭黄鹂 【下联】绵绵秋雨润禾苗，处处山林映玉蝉
> 【上联】漠漠水田飞白鹭，阴阴夏木啭黄鹂 【下联】依依山径落斜阳，袅袅炊烟绕翠竹
> 
> 【上联】五岭横云一片青，衡山积雪终年白 【下联】九州铺锦八方绿，林海堆红满眼春
> 【上联】五岭横云一片青，衡山积雪终年白 【下联】双峰映日十分碧，函谷春深几度红
> 
> 【上联】洞庭浩渺通长江，春来水涨连天碧 【下联】华阁崔巍迎盛会，时过车奔遍地红
> 【上联】慷慨歌燕市，从容作楚囚 【下联】清音醉杏坛，寂寞成唐诗
> 【上联】赤橙黄绿青蓝紫，谁持彩练当空舞 【下联】柴米油盐酱醋茶，客为力军作秀言
> 
> 【上联】茫茫九派流中国，沉沉一线穿南北 【下联】滔滔三江溯太行，滚浩万年贯古今
> 【上联】茫茫九派流中国，沉沉一线穿南北 【下联】浩浩千春耀上京，滚滚三江舞东西
> 【上联】茫茫九派流中国，沉沉一线穿南北 【下联】荡荡东洋过大江，滚滚千流过古今
> 【上联】茫茫九派流中国，沉沉一线穿南北 【下联】悠悠三湾锁西洋，滚滚千商过东西
> 
> 【上联】横空出世，莽昆仑，阅尽人间春色 【下联】下笔挥毫，成巨匠，绘出生态蓝图
> 【上联】飞起玉龙三百万，搅得周天寒彻 【下联】勾起渭河数千年，汇来秦土风情
> 【上联】飞起玉龙三百万，搅得周天寒彻 【下联】携来佛法五千言，引来妙谛玄机
> 【上联】我失骄杨君失柳，杨柳轻扬直上重霄九 【下联】春回大地雪迎雷，地冰乍起先苏万物锦
> 【上联】夜长天色总难明，寂寞披衣起坐数寒星 【下联】人静心灰都是幻，相思枕席轻敲几尺丝
> 【上联】夜长天色总难明，寂寞披衣起坐数寒星 【下联】人在画图空有趣，从容拄杖谈玄一醉开
> 【上联】夜长天色总难明，寂寞披衣起坐数寒星 【下联】金风玉露悄然冷，相思倚枕听啼无归人
> 【上联】六月天兵征腐恶，万丈长缨要把鲲鹏缚 【下联】一支玉笔写春秋，千年遗恨永铭将士碑
> 
> 【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】五千兵戈俱喧阗，水归淮北空余屈子魂
> 【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】千余老幼尽欢颜，联惊海外长怀赵与韩
> 【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】三千志士竞登攀，功成世界全凭武与文 【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】三千豪杰竞风流，舟行淮北犹歌宋与唐
> 【上联】百万工农齐踊跃，席卷江西直捣湘和鄂 【下联】七旬岁月竞风流，梦牵河北长扬楚与吴
> 【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】我来江畔谒崇陵，遗烈八年壮国威 注：崇陵是光绪皇帝爱新觉罗.载湉和叶赫那拉·静芬（隆裕太后）的合葬陵寝 【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】回首江山换新颜，春花一样笑杨梅
> 【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】重归海岛护同盟，风雨千秋祭祖师
> 
> 【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】且邀明月饮新醪，玉液千杯酹泰山 注：醪， 新酿的酒；酹，把酒浇在地上，表示祭奠
> 【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】今观国粹谱新篇，联对千家颂党恩
> 【上联】此去泉台招旧部，旌旗十万斩阎罗 【下联】重归梓里吊忠魂，天地三千开后人
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】帝无前事佐明主，却图一战扫烟云
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】人生向上多自力，始终一战统山河
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】死犹未免埋白骨，亦如一抔葬忠魂
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】人心臣首怀赤胆，未能一死竟平生
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】人思此处访遗庙，未经千载是英雄
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】不由后死赴江汉，岂独一败论英雄
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】谁似臣心报国门？至今百战识英雄
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】自悲吾辈失青鬓，竟成千古痛元君
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】我来仙界横紫气，定披七彩绣河山
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】不为世界哭元老，且持三字表心胸
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】世风余韵遗青史，岂惟五代识君臣
> 【上联】天命吾身踏黄泉，定起万军夺阴曹 【下联】世间此地留忠骨，长教千载祀英雄

请问一下你进行预训练了吗？？用的话，是使用的 多gpu训练吗？？是采用模型并行的方法吗？？

**Comment by huanghonggit** [comment]
@ScottishFold007 Hello, can you share how you made the tf  model to pytorch, please!
