### ISSUE TITLE
[Discussion] Vocabulary file

### ISSUE THREAD

**Issue by mananeau** [imcaspar/gpt2-ml#62]
Hi all,

Thanks for the cool contribution :) I'm trying to use your repo to pre-train GPT-2 from scratch on other languages (not English nor Chinese). Could you say a bit more on how you generated your vocabulary (which library you used? sentencepiece?)? Also, what kind of vocabulary is it (BPE, etc...)?

If I understood well, when I have my vocab file for my language, I can then create the tfrecords for my data and run the train.py file?

Thanks a lot in advance!

**Comment by leejason** [comment]
+1

**Comment by mananeau** [comment]
> +1

I actually figured it out, it's a WordPiece vocab. You can create directly, for instance, with the tokenizers library from hugging face. :)
