### ISSUE TITLE
请问预训练用的语料可以分享一下吗 或者说明一下语料清洗的方法

### ISSUE THREAD

**Issue by sugarshaw95** [imcaspar/gpt2-ml#70]
RT,因为机器配置的问题没法用放出来的预训练模型finetune,想尝试用同样的语料在小一些的模型配置下从头训练.

**Comment by imcaspar** [comment]
训练语料来源 readme 里有描述
数据预处理可以参考 https://github.com/imcaspar/gpt2-ml/tree/master/dataset
