### ISSUE TITLE
[Discussion] gpu预测速度

### ISSUE THREAD

**Issue by rivaldinho123** [imcaspar/gpt2-ml#74]
模型在v100 GPU上直接利用demo.py进行预测，发现在min_len设置为150时，每生成一个sample需要80-90s，即使把min_len缩短为10，每生成一个sample也需要30s左右，请问这是正常的吗？如果是的话有什么可以加速预测的设置或者方法吗？

谢谢。

**Comment by rivaldinho123** [comment]
另外在生成sample的时间里，虽然在GPU指定的卡上能看到预测进程，但只占用了几百M显存，而且观察GPU的利用率一直是0%。。。不知道是不是哪里使用有些问题

**Comment by rivaldinho123** [comment]
确实是没有使用gpu的问题，已解决

**Comment by kunpeng199494** [comment]
请问你是怎么解决的
