### ISSUE TITLE
[Discussion] 词表文件

### ISSUE THREAD

**Issue by rivaldinho123** [imcaspar/gpt2-ml#75]
请问想利用30G训练数据的那个版本进行finetuning的话，目前的prepare_data.py好像词表不对应？请问prepare_data.py中需要做什么调整呢？把词表文件从bert的换成clue的就可以吗？还有什么其他地方要改动吗？
@imcaspar

**Comment by imcaspar** [comment]
除了词表其他地方不需要更改了
