### ISSUE TITLE
通过GPT-2模型给小学生写参考作文的可行性？

### ISSUE THREAD

**Issue by zgxtao** [imcaspar/gpt2-ml#85]
现在在构思一款基于GPT-2模型的“短文写作”产品，现在有一些业务层面的 构想，想向你请教下，不知是否可以达到预期效果：

1.业务目标：为9年义务教育阶段的学生输出参考70分水平（概数）的短文，让缺乏作文思路的学生有一个参考，并且让学生们也参与到候选短文的打分中，实现教学相
                     长，又让写作算法可以不断进化

2.业务流程：a(服务流程）.一个用户提交一句话开头，系统输出若干个候选短文样例，用户标出样例中最满意的（采用的参考作文）
                     b(系统自我优化）. 系统推送一条已生成的候选短文样例，给若干个用户，并且得到这些用户对它的打分（例如5分制），将打分作为新的训练数据输入系
                        统，让系统逐渐输出越来越高分的短文。
3.局限性预判：虽然有上面的流程，但是作为服务仍然可以预见到，输出的短文肯定很难一开始就给到用户很满意的结果，甚至很长时间也不能进化到用户50%概率满意
                      的程度，所以这项服务的定位是参考，而非替代，旨在给出一些写作文的思路

这样，就有两个问题请教，
1.利用服务流程b，是否可以让这套写作系统不断自我优化，输出质量越来越接近用户的心意？
2.如果可以，用户的打分结果应该如何嵌入到算法步骤中，实现最好的fine-tune？

**Comment by ScottishFold007** [comment]
首先你得有大量的训练样本，即各个分数的学生作文作为训练样本。
