### ISSUE TITLE
Bert 词汇表[Discussion] your question

### ISSUE THREAD

**Issue by QiuSYang** [imcaspar/gpt2-ml#87]
15G语料库使用BERT 21128大小的词汇表训练出来的1.5B参数预训练模型，使用的config文件是哪个，我看了项目提供的三个config文件没有一个vocab_size的大小等于21128，还是说作者就是使用bert config。希望作者可以回答，万分感谢。

**Comment by imcaspar** [comment]
可以看下这个 release https://github.com/imcaspar/gpt2-ml/releases/tag/v0.5
