### ISSUE TITLE
[Discussion] 关于中文预训练模型细节

### ISSUE THREAD

**Issue by syw1996** [imcaspar/gpt2-ml#94]
您好！在readme中目前只公布了模型训练步数以及TPU的型号，并未详细说明需要TPU的数量以及batch size设置。请问这些模型训练详情是否方便公布，非常感谢。

**Comment by imcaspar** [comment]
可以参考这里的参数设置 https://github.com/imcaspar/gpt2-ml/tree/master/train

**Comment by syw1996** [comment]
> 可以参考这里的参数设置 https://github.com/imcaspar/gpt2-ml/tree/master/train

多谢
