### ISSUE TITLE
[Discussion] colab无法运行Couldn't download the file 模型

### ISSUE THREAD

**Issue by xuxiaoyaoo** [imcaspar/gpt2-ml#96]
/content/gpt2-ml
models/mega/model.c     [ <=>                ]   3.02K  --.-KB/s    in 0s      
Couldn't download the file :-(
model.ckpt-220000.i 100%[===================>]  25.56K   141KB/s    in 0.2s    
model.ckpt-220000.m 100%[===================>]  41.99M  11.7MB/s    in 3.8s    
Download finished.
昨天能用了，今天又这样了
![微信截图_20201027160505](https://user-images.githubusercontent.com/73153206/97273597-8dd5cb80-186e-11eb-8460-97aa660dbfba.png)
![微信截图_20201027160810](https://user-images.githubusercontent.com/73153206/97273683-9fb76e80-186e-11eb-877b-d46ca878cf86.png)

**Comment by imcaspar** [comment]
我这里没能复现这个问题
如果再遇到可以验一下文件的 sha256 和 readme 中是否一致
!sha256sum models/mega/model.ckpt-220000.data-00000-of-00001

**Comment by xuxiaoyaoo** [comment]
!sha256sum models/mega/model.ckpt-220000.data-00000-of-00001
运行结果：dcdb8245236d2726b2895aa92a09311fb141149621a8c08dbbd17129251462f0  models/mega/model.ckpt-220000.data-00000-of-00001

**Comment by xuxiaoyaoo** [comment]
执行注释里的代码就好了!python scripts/down_gdrive_file.py -file_id='1mT_qCQg4AWnAXTwKfsyyRWCRpgPrBJS3' -file_path='models/mega/model.ckpt-220000.data-00000-of-00001'

**Comment by imcaspar** [comment]
@xuxiaoyaoo sha256 值和 readme 里不同，应该是模型文件下载的问题
down_gdrive_file.py 走的是 gcp 官方的包下载更稳定些，缺点是多一次授权
